export const ErrorCodes = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  EMPLOYEE_NOT_FOUND: 'EMPLOYEE_NOT_FOUND',
  DUPLICATE_EMPLOYEE_CODE: 'DUPLICATE_EMPLOYEE_CODE',
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  DEPARTMENT_NOT_FOUND: 'DEPARTMENT_NOT_FOUND',
  DESIGNATION_NOT_FOUND: 'DESIGNATION_NOT_FOUND',
  DUPLICATE_ASSIGNMENT: 'DUPLICATE_ASSIGNMENT',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;
