export const ErrorCodes = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  OFFICE_NOT_FOUND: 'OFFICE_NOT_FOUND',
  NO_ACTIVE_POLYGON: 'NO_ACTIVE_POLYGON',
  INVALID_POLYGON: 'INVALID_POLYGON',
  DUPLICATE_OFFICE_CODE: 'DUPLICATE_OFFICE_CODE',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;
