export const ErrorCodes = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',

  ATTENDANCE_ALREADY_ACTIVE: 'ATTENDANCE_ALREADY_ACTIVE',
  ATTENDANCE_ALREADY_COMPLETED: 'ATTENDANCE_ALREADY_COMPLETED',
  NO_ACTIVE_SESSION: 'NO_ACTIVE_SESSION',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  NOT_FOUND: 'NOT_FOUND',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  CHECKOUT_WHILE_PAUSED_NOT_ALLOWED: 'CHECKOUT_WHILE_PAUSED_NOT_ALLOWED',

  EMPLOYEE_NOT_ASSIGNED_TO_OFFICE: 'EMPLOYEE_NOT_ASSIGNED_TO_OFFICE',
  OUTSIDE_GEOFENCE: 'OUTSIDE_GEOFENCE',
  STILL_INSIDE_GEOFENCE: 'STILL_INSIDE_GEOFENCE',
  LOCATION_ACCURACY_TOO_LOW: 'LOCATION_ACCURACY_TOO_LOW',

  DUPLICATE_CLIENT_EVENT_ID: 'DUPLICATE_CLIENT_EVENT_ID',
  CONFLICT: 'CONFLICT',

  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
